// frontend-react/src/components/ProductList.tsx
import React, { useEffect, useState } from 'react';
import { Product } from '../types';
import { productService } from '../services/productService';
import './ProductList.css';

const ProductList: React.FC = () => {
  const [products, setProducts] = useState<Product[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    loadProducts();
  }, []);

  const loadProducts = async () => {
    try {
      setLoading(true);
      const data = await productService.getAllProducts();
      setProducts(data);
      setError(null);
    } catch (err) {
      setError('Failed to load products. Please try again later.');
      console.error('Error loading products:', err);
    } finally {
      setLoading(false);
    }
  };

  if (loading) {
    return <div className="loading">Loading products...</div>;
  }

  if (error) {
    return <div className="error">{error}</div>;
  }

  return (
    <div className="product-list-container">
      <h2>Products</h2>
      <div className="product-grid">
        {products.map((product) => (
          <div key={product.id} className="product-card">
            <img 
              src={product.imageUrl} 
              alt={product.name} 
              className="product-image"
            />
            <h3>{product.name}</h3>
            <p className="category">{product.category}</p>
            <p className="description">{product.description}</p>
            <div className="price-section">
              <span className="price">${product.price}</span>
              {product.discountPrice && (
                <span className="discount-price">${product.discountPrice}</span>
              )}
            </div>
            {product.rating && (
              <div className="rating">
                ⭐ {product.rating} ({product.reviewCount} reviews)
              </div>
            )}
            <button className="add-to-cart-btn">Add to Cart</button>
          </div>
        ))}
      </div>
    </div>
  );
};

export default ProductList;

// frontend-angular/src/app/components/product-list/product-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ProductService, Product } from '../../services/product.service';

@Component({
  selector: 'app-product-list',
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.css']
})
export class ProductListComponent implements OnInit {
  products: Product[] = [];
  loading = false;

  constructor(private productService: ProductService) {}

  ngOnInit(): void {
    this.loadProducts();
  }

  loadProducts(): void {
    this.loading = true;
    this.productService.getAllProducts().subscribe({
      next: (data) => {
        this.products = data;
        this.loading = false;
      },
      error: (error) => {
        console.error('Error loading products:', error);
        this.loading = false;
      }
    });
  }
}

<div class="product-list-container">
  <h2>Products</h2>
  
  <div *ngIf="loading" class="loading">Loading products...</div>
  
  <div class="product-grid" *ngIf="!loading">
    <div class="product-card" *ngFor="let product of products">
      <img [src]="product.imageUrl" [alt]="product.name" class="product-image">
      <h3>{{ product.name }}</h3>
      <p class="category">{{ product.category }}</p>
      <p class="description">{{ product.description }}</p>
      <div class="price-section">
        <span class="price">${{ product.price }}</span>
        <span class="discount-price" *ngIf="product.discountPrice">
          ${{ product.discountPrice }}
        </span>
      </div>
      <div class="rating" *ngIf="product.rating">
        ⭐ {{ product.rating }} ({{ product.reviewCount }} reviews)
      </div>
      <button class="add-to-cart-btn">Add to Cart</button>
    </div>
  </div>
</div>
